//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBankModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Transfers = new HashSet<Transfer>();
            this.Transfers1 = new HashSet<Transfer>();
        }
    
        public int ID { get; set; }
        public int CreditInst { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastModDate { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual ICollection<Transfer> Transfers1 { get; set; }
    }
}
